name: Console.log Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  check-console-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Settings for pull_request events

    - name: Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v39.2.1

    - name: Find specific word
      id: find-specific-word
      run: |
        # Create a variable to store the results
        results=""

        # Find the word "console.log" in the modified files
        for file in ${{ steps.changed-files.outputs.modified_files }}; do
          resultGrep=$(grep -n 'console.log' "$file" || true)
          if [ $? -eq 0 ] && [ -n "$resultGrep" ]; then
            # Escape single quotes in results
            echo "${results}" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`js\n" >> $GITHUB_STEP_SUMMARY
            echo "// File: $file\n" >> $GITHUB_STEP_SUMMARY
            
            resultGrep="${resultGrep//\'/\'\'\"}"
            
            echo "\n\`\`\`\n\n" >> $GITHUB_STEP_SUMMARY
          fi
        done

        # Store the results in GITHUB_OUTPUT
        # echo "RESULTS=$results" >> "$GITHUB_OUTPUT"

    - name: Add Comment Pull
      env:
        COMMENTS_RESULTS: ${{ steps.find-specific-word.outputs.GITHUB_STEP_SUMMARY }}
      if: steps.find-specific-word.outputs.GITHUB_STEP_SUMMARY != ''
      run: |
        # Get the results
        comment_results="$COMMENTS_RESULTS"
    
        # Build the comment with Markdown format
        comment="### Found \`console.log\` in:\n\n$comment_results"
        echo "$comment"
    
        # Add the comment to the pull request
        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\":\"$comment\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

        exit 1
