name: Console.log Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  check-console-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: List modified files
      run: |
        # Lista de archivos modificados en la solicitud de extracción
        git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep -E '\.tsx?$'
    
    - name: Show content of modified files
      run: |
        # Mostrar el contenido de los archivos modificados
        while read -r file; do
          echo "Contents of $file:"
          cat $file
        done
    
    - name: Find console.log
      run: |
        # Encontrar declaraciones console.log en los archivos modificados
        while read -r file; do
          if grep -q 'console\.log' "$file"; then
            echo "console.log statements found in $file"
            exit 1
          fi
        done < modified_files.txt || echo "No console.log statements found"
