name: Console.log Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  check-console-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Configuración para pull_request eventos
    
    - name: Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v39.2.1
    
    - name: Show content of modified files
      run: |
        # Mostrar el contenido de los archivos modificados
        cat ${{ steps.changed-files.outputs.modified_files }}
    
    - name: Find console.log
      run: |
        # Encontrar declaraciones console.log en los archivos modificados
        while read -r file; do
          if grep -q 'console\.log' "$file"; then
            echo "console.log statements found in $file"
            exit 1
          fi
        done < ${{ steps.changed-files.outputs.modified_files }} || echo "No console.log statements found"
