name: Console.log Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  check-console-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Configuración para pull_request eventos
    
    - name: Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v39.2.1
    
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done
    
    - name: Find specific word
      run: |
        # Encontrar la palabra "console.log" en los archivos modificados
        for file in ${{ steps.changed-files.outputs.modified_files }}; do
          if grep -q 'console.log' "$file"; then
            echo "Found 'console.log' in $file"
            # Puedes agregar acciones adicionales aquí si se encuentra la palabra
          fi
        done
