name: Console.log Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  check-console-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Configuración para pull_request eventos
    
    - name: Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v39.2.1

    - name: Find specific word
      run: |
        # Encontrar la palabra "console.log" en los archivos modificados
        for file in ${{ steps.changed-files.outputs.modified_files }}; do
          resultGrep=$(grep -n 'console.log' "$file")
          if [ $? -eq 0 ]; then
            echo "Found 'console.log' in $file"
            echo "$resultGrep"
          else
            echo "No 'console.log' found in $file"
          fi
        done
