name: Console.log Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  check-console-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Settings for pull_request events

    - name: Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v39.2.1

    - name: Find specific word
      id: find-specific-word
      run: |
        # Create a variable to store the results
        results=""

        # Encontrar la palabra "console.log" en los archivos modificados
        for file in ${{ steps.changed-files.outputs.modified_files }}; do
          resultGrep=$(grep -n 'console.log' "$file" || true)
          if [ $? -eq 0 ] && [ -n "$resultGrep" ]; then
            results="${results}\`\`\`js\n// File: $file\n$resultGrep\`\`\`\n\n"
          fi
        done

        # Store the results in GITHUB_OUTPUT
        echo "RESULTS=$results" >> "$GITHUB_OUTPUT"

    - name: Add Comment Pull
      env:
        COMMENTS_RESULTS: ${{ steps.find-specific-word.outputs.RESULTS }}
      if: steps.find-specific-word.outputs.RESULTS != ''
      run: |
        # Get the results
        comment_results="$COMMENTS_RESULTS"
        echo $comment_results
    
        # Build the comment with Markdown format
        comment="### Found \`console.log\` in:\n\n$comment_results"
    
        # Agregar el comentario a la solicitud de extracción
        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\":\"$comment\"}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments"

